"""Layer 2 relation-family specialists.

Implemented: **M12 Numeric Specialist** (``hasCapacity``, ``hasArea``) and
**M13 Large-Open-Set Specialist** (``awardWonBy``), **M14 Null/Temporal
Specialist** (``personHasCityOfDeath``) and **M15 Small-Set Closure
Specialist** (``countryLandBordersCountry``, ``companyTradesAtStockExchange``).
Layer 2 is complete.

They are **siblings over disjoint relations**: any may be enabled without the
others, and none imports another. Modules 14 and 15 both use
:mod:`cover_kbc.specialists.cross_family`, a shared primitive that belongs to
neither. Nothing here is a placeholder for the unimplemented modules - the
consensus engine, the verifier suite and the control modules get their files
when they get their milestones.
"""

from cover_kbc.specialists.cross_family import (
    CrossFamilyDecision,
    decide_cross_family,
    distinct_families,
)
from cover_kbc.specialists.small_set_registry import (
    SMALL_SET_RELATIONS,
    SMALL_SET_VERSION,
    NON_MENTION_CONTRACT_RULES,
    SmallSetRelationSpec,
    UnsupportedSmallSetRelation,
    check_small_set_registry_consistency,
    handles as small_set_handles,
    small_set_spec,
)
from cover_kbc.specialists.small_set_registry import (
    mention_taxonomy as small_set_mention_taxonomy,
)
from cover_kbc.specialists.small_set_registry import (
    probe_catalogue as small_set_probe_catalogue,
)
from cover_kbc.specialists.small_set_specialist import (
    GATE_SYSTEM_PROMPT,
    SMALL_SET_SYSTEM_PROMPT,
    SmallSetSpecialist,
    SmallSetSpecialistConfig,
    SmallSetSpecialistError,
    build_closure_signals,
    build_pending_checks,
    build_small_set_specialist,
    classify_listing_type,
    classify_temporal_status,
    evaluate_cross_family_trigger,
    extract_candidates,
    jaccard,
    parse_listing_status,
    read_listing_gate,
    split_candidates,
)
from cover_kbc.specialists.small_set_specialist import (
    build_occurrences as build_small_set_occurrences,
)
from cover_kbc.specialists.small_set_specialist import (
    classify_mention as classify_small_set_mention,
)
from cover_kbc.specialists.small_set_specialist import (
    normalise_surface as normalise_small_set_surface,
)
from cover_kbc.specialists.small_set_types import (
    BorderMentionKind,
    ClosureSignals,
    ClosureSnapshot,
    CrossFamilyTrigger,
    ListingExistenceStatus,
    ListingGateReading,
    ListingGateState,
    ListingStatusObservation,
    ListingTemporalStatus,
    ListingType,
    PendingCheck,
    PendingCheckKind,
    PendingCheckReason,
    SmallSetCandidateObservation,
    SmallSetCandidateOccurrence,
    SmallSetObservationSource,
    SmallSetParseStatus,
    SmallSetProbe,
    SmallSetProbeFamily,
    SmallSetRelationKind,
    SmallSetSpecialistPlan,
    SmallSetSpecialistResult,
    StockMentionKind,
)

from cover_kbc.specialists.null_temporal_registry import (
    DEATH_LOCALITY_CUES,
    LOCALITY_CUES,
    NO_KNOWN_LOCALITY_CUES,
    NON_LOCALITY_CONTRACT_RULES,
    NULL_TEMPORAL_RELATIONS,
    NULL_TEMPORAL_VERSION,
    STATUS_CUES,
    LocalityCue,
    NullTemporalRelationSpec,
    ProbeTemplate,
    StatusCue,
    UnsupportedNullTemporalRelation,
    check_null_temporal_registry_consistency,
    locality_taxonomy,
    null_temporal_spec,
)
from cover_kbc.specialists.null_temporal_registry import (
    probe_catalogue as null_temporal_probe_catalogue,
)
from cover_kbc.specialists.null_temporal_specialist import (
    LOCALITY_SYSTEM_PROMPT,
    STATUS_SYSTEM_PROMPT,
    NullTemporalSpecialist,
    NullTemporalSpecialistConfig,
    NullTemporalSpecialistError,
    build_null_evidence,
    build_null_temporal_specialist,
    classify_locality,
    extract_localities,
    normalise_locality,
    asserts_relation_level_absence,
    is_epistemic_abstention,
    is_explicit_empty_sentinel,
    parse_death_status,
    read_gate,
    states_no_known_locality,
)
from cover_kbc.specialists.null_temporal_specialist import (
    build_occurrences as build_locality_occurrences,
)
from cover_kbc.specialists.null_temporal_types import (
    DeathStatus,
    DeathStatusObservation,
    GateReading,
    GateState,
    LocalityMentionKind,
    LocalityObservation,
    LocalityOccurrence,
    LocalityProbeFamily,
    NullEvidenceKind,
    NullEvidenceState,
    NullTemporalParseStatus,
    NullTemporalProbe,
    NullTemporalSpecialistPlan,
    NullTemporalSpecialistResult,
    RecallFamily,
    StatusProbeFamily,
)

from cover_kbc.specialists.large_set_registry import (
    AWARD_MENTION_CUES,
    LARGE_SET_RELATIONS,
    LARGE_SET_VERSION,
    FacetTemplate,
    LargeSetRelationSpec,
    MentionCue,
    UnsupportedLargeSetRelation,
    check_large_set_registry_consistency,
    facet_taxonomy,
    facets_for,
    large_set_spec,
    mention_taxonomy,
)
from cover_kbc.specialists.large_set_specialist import (
    LARGE_SET_SYSTEM_PROMPT,
    LargeSetSpecialist,
    LargeSetSpecialistConfig,
    LargeSetSpecialistError,
    build_facet_states,
    build_large_set_specialist,
    build_occurrences,
    classify_mention,
    extract_mentions,
    normalise_surface,
    split_mentions,
)
from cover_kbc.specialists.large_set_types import (
    AwardCandidateObservation,
    AwardMentionKind,
    CandidateOccurrence,
    FacetSearchState,
    LargeSetFacet,
    LargeSetFacetKind,
    LargeSetParseStatus,
    LargeSetProbe,
    LargeSetSpecialistPlan,
    LargeSetSpecialistResult,
    MentionSource,
)

from cover_kbc.specialists.numeric_registry import (
    NUMERIC_RELATIONS,
    SPECIALIST_VERSION,
    NumericRelationSpec,
    SemanticCue,
    UnsupportedNumericRelation,
    check_numeric_registry_consistency,
    handles,
    numeric_spec,
    semantic_taxonomy,
)
from cover_kbc.specialists.numeric_specialist import (
    NUMERIC_SYSTEM_PROMPT,
    NumericSpecialist,
    NumericSpecialistConfig,
    NumericSpecialistError,
    build_clusters,
    build_numeric_specialist,
    canonical_units,
    canonicalise,
    classify_semantic_kind,
    cross_unit_checks,
    dispersion_of,
    extract_observations,
    probe_catalogue,
)
from cover_kbc.specialists.numeric_types import (
    CrossUnitCheck,
    NumericClusterState,
    NumericObservation,
    NumericParseStatus,
    NumericProbe,
    NumericProbeFamily,
    NumericSemanticKind,
    NumericSpecialistPlan,
    NumericSpecialistResult,
    ObservationSource,
)

__all__ = [
    "AWARD_MENTION_CUES",
    "BorderMentionKind",
    "ClosureSignals",
    "ClosureSnapshot",
    "CrossFamilyDecision",
    "CrossFamilyTrigger",
    "evaluate_cross_family_trigger",
    "GATE_SYSTEM_PROMPT",
    "ListingExistenceStatus",
    "ListingGateReading",
    "ListingGateState",
    "ListingStatusObservation",
    "ListingTemporalStatus",
    "ListingType",
    "NON_MENTION_CONTRACT_RULES",
    "PendingCheck",
    "PendingCheckKind",
    "PendingCheckReason",
    "SMALL_SET_RELATIONS",
    "SMALL_SET_SYSTEM_PROMPT",
    "SMALL_SET_VERSION",
    "SmallSetCandidateObservation",
    "SmallSetCandidateOccurrence",
    "SmallSetObservationSource",
    "SmallSetParseStatus",
    "SmallSetProbe",
    "SmallSetProbeFamily",
    "SmallSetRelationKind",
    "SmallSetRelationSpec",
    "SmallSetSpecialist",
    "SmallSetSpecialistConfig",
    "SmallSetSpecialistError",
    "SmallSetSpecialistPlan",
    "SmallSetSpecialistResult",
    "StockMentionKind",
    "UnsupportedSmallSetRelation",
    "build_closure_signals",
    "build_pending_checks",
    "build_small_set_occurrences",
    "build_small_set_specialist",
    "check_small_set_registry_consistency",
    "classify_listing_type",
    "classify_small_set_mention",
    "classify_temporal_status",
    "decide_cross_family",
    "distinct_families",
    "extract_candidates",
    "jaccard",
    "normalise_small_set_surface",
    "parse_listing_status",
    "read_listing_gate",
    "small_set_handles",
    "small_set_mention_taxonomy",
    "small_set_probe_catalogue",
    "small_set_spec",
    "split_candidates",
    "DEATH_LOCALITY_CUES",
    "DeathStatus",
    "DeathStatusObservation",
    "GateReading",
    "GateState",
    "LOCALITY_CUES",
    "LOCALITY_SYSTEM_PROMPT",
    "LocalityCue",
    "LocalityMentionKind",
    "LocalityObservation",
    "LocalityOccurrence",
    "LocalityProbeFamily",
    "NON_LOCALITY_CONTRACT_RULES",
    "NO_KNOWN_LOCALITY_CUES",
    "NULL_TEMPORAL_RELATIONS",
    "NULL_TEMPORAL_VERSION",
    "NullEvidenceKind",
    "NullEvidenceState",
    "NullTemporalParseStatus",
    "NullTemporalProbe",
    "NullTemporalRelationSpec",
    "NullTemporalSpecialist",
    "NullTemporalSpecialistConfig",
    "NullTemporalSpecialistError",
    "NullTemporalSpecialistPlan",
    "NullTemporalSpecialistResult",
    "ProbeTemplate",
    "RecallFamily",
    "STATUS_CUES",
    "STATUS_SYSTEM_PROMPT",
    "StatusCue",
    "StatusProbeFamily",
    "UnsupportedNullTemporalRelation",
    "build_locality_occurrences",
    "build_null_evidence",
    "build_null_temporal_specialist",
    "check_null_temporal_registry_consistency",
    "classify_locality",
    "extract_localities",
    "locality_taxonomy",
    "normalise_locality",
    "null_temporal_probe_catalogue",
    "null_temporal_spec",
    "asserts_relation_level_absence",
    "is_epistemic_abstention",
    "is_explicit_empty_sentinel",
    "parse_death_status",
    "read_gate",
    "states_no_known_locality",
    "AwardCandidateObservation",
    "AwardMentionKind",
    "CandidateOccurrence",
    "CrossUnitCheck",
    "FacetSearchState",
    "FacetTemplate",
    "LARGE_SET_RELATIONS",
    "LARGE_SET_SYSTEM_PROMPT",
    "LARGE_SET_VERSION",
    "LargeSetFacet",
    "LargeSetFacetKind",
    "LargeSetParseStatus",
    "LargeSetProbe",
    "LargeSetRelationSpec",
    "LargeSetSpecialist",
    "LargeSetSpecialistConfig",
    "LargeSetSpecialistError",
    "LargeSetSpecialistPlan",
    "LargeSetSpecialistResult",
    "MentionCue",
    "MentionSource",
    "UnsupportedLargeSetRelation",
    "build_facet_states",
    "build_large_set_specialist",
    "build_occurrences",
    "check_large_set_registry_consistency",
    "classify_mention",
    "extract_mentions",
    "facet_taxonomy",
    "facets_for",
    "large_set_spec",
    "mention_taxonomy",
    "normalise_surface",
    "split_mentions",
    "NUMERIC_RELATIONS",
    "NUMERIC_SYSTEM_PROMPT",
    "NumericClusterState",
    "NumericObservation",
    "NumericParseStatus",
    "NumericProbe",
    "NumericProbeFamily",
    "NumericRelationSpec",
    "NumericSemanticKind",
    "NumericSpecialist",
    "NumericSpecialistConfig",
    "NumericSpecialistError",
    "NumericSpecialistPlan",
    "NumericSpecialistResult",
    "ObservationSource",
    "SPECIALIST_VERSION",
    "SemanticCue",
    "UnsupportedNumericRelation",
    "build_clusters",
    "build_numeric_specialist",
    "canonical_units",
    "canonicalise",
    "check_numeric_registry_consistency",
    "classify_semantic_kind",
    "cross_unit_checks",
    "dispersion_of",
    "extract_observations",
    "handles",
    "numeric_spec",
    "probe_catalogue",
    "semantic_taxonomy",
]
