"""Layer 6 control plane - Module 20's budget scheduler and Module 21's planner.

Named ``control`` rather than ``controller`` because core Module 7 already owns
``cover_kbc.controller`` and remains the production authority. Module 20 is a
**shadow** resource planner beside it: it reasons about neural calls, allocates
envelopes and holds precharges, and it makes no call, chooses no action and
decrements no production budget.

Module 21 sits beside it, also shadow: it ranks *actions* by expected value and
returns one or STOP, and executes nothing. Module 7 remains the production
controller and Module 8 the finaliser.
"""

from cover_kbc.control.budget_accounting import (
    BudgetLedger,
    classify_generation_record,
    generation_call,
    replay_physical_calls,
    score_label_call,
    specialist_verification_plan,
    structural_check_plan,
    total_calls,
)
from cover_kbc.control.action_catalog import (
    CATALOG_VERSION,
    ActionOwner,
    CatalogExclusion,
    ControlActionCandidate,
    ExclusionReason,
    build_action_catalog,
    m7_actions,
    m11_actions,
    m17_actions,
    m18_actions,
    owner_action_families,
    specialist_actions,
)
from cover_kbc.control.layer6_integration import (
    LAYER6_VERSION,
    NO_EXECUTION_MARKER,
    Layer6ControlState,
    Layer6Integrator,
    collect_catalog,
)
from cover_kbc.control.historical_bins import (
    ESTIMATE_UNITS,
    HISTORY_SCHEMA_VERSION,
    REQUIRED_ESTIMATES,
    HistoricalActionBin,
    HistoricalBinPackage,
    StateBinningSpec,
    SuccessorStat,
    load_history,
    state_bin_key,
    validate_bins,
)
from cover_kbc.control.micro_planner import (
    MicroPlanner,
    MicroPlannerConfig,
    build_micro_planner,
    core_action_family,
    load_planner_calibration,
    state_signature,
    utility,
)
from cover_kbc.control.planner_types import (
    PLANNER_DISCLAIMER,
    PLANNER_VERSION,
    ActionExecutionStatus,
    ActionFamily,
    ActionUtilityBreakdown,
    DecisionKind,
    DeniedAction,
    EstimateSource,
    MicroPlannerDecision,
    PlannerActionCandidate,
    PlannerCalibration,
    PlannerError,
    PlannerStateSnapshot,
    StopReason,
    SuccessorDiagnostics,
)
from cover_kbc.control.budget_types import (
    COST_SCHEMA_VERSION,
    RESOURCE_DISCLAIMER,
    SCHEDULER_VERSION,
    ActionCost,
    BudgetActionDescriptor,
    BudgetDemandTier,
    BudgetDenial,
    BudgetDenialReason,
    BudgetEnvelope,
    BudgetLedgerState,
    BudgetPressure,
    BudgetReservation,
    BudgetSchedulerError,
    BudgetSettlement,
    BudgetSpendClass,
    CacheDisposition,
    CalibrationSource,
    CallKind,
    CoreBudgetSnapshot,
    PhysicalCallRecord,
    QualitativeRelationBudgetPolicy,
    RelationBudgetCalibration,
    RelationBudgetPlan,
    RelationBudgetResult,
    ReplayReconciliation,
    ReservationStatus,
    RiskBudgetDemand,
    SpecialReservePurpose,
    SubCall,
    reservation_id,
)
from cover_kbc.control.relation_budget import (
    RELATION_BUDGET_POLICIES,
    RelationBudgetConfig,
    RelationBudgetScheduler,
    build_plan,
    build_relation_budget_scheduler,
    load_calibrations,
    relation_policy,
    risk_demand,
)

__all__ = [
    "ActionCost",
    "ActionExecutionStatus",
    "ActionFamily",
    "ActionOwner",
    "ActionUtilityBreakdown",
    "BudgetActionDescriptor",
    "BudgetDemandTier",
    "BudgetDenial",
    "BudgetDenialReason",
    "BudgetEnvelope",
    "BudgetLedger",
    "BudgetLedgerState",
    "BudgetPressure",
    "BudgetReservation",
    "BudgetSchedulerError",
    "BudgetSettlement",
    "BudgetSpendClass",
    "CATALOG_VERSION",
    "COST_SCHEMA_VERSION",
    "CacheDisposition",
    "CalibrationSource",
    "CallKind",
    "CatalogExclusion",
    "ControlActionCandidate",
    "CoreBudgetSnapshot",
    "DecisionKind",
    "DeniedAction",
    "ESTIMATE_UNITS",
    "EstimateSource",
    "ExclusionReason",
    "HISTORY_SCHEMA_VERSION",
    "HistoricalActionBin",
    "HistoricalBinPackage",
    "LAYER6_VERSION",
    "Layer6ControlState",
    "Layer6Integrator",
    "MicroPlanner",
    "MicroPlannerConfig",
    "MicroPlannerDecision",
    "NO_EXECUTION_MARKER",
    "PLANNER_DISCLAIMER",
    "PLANNER_VERSION",
    "PhysicalCallRecord",
    "PlannerActionCandidate",
    "PlannerCalibration",
    "PlannerError",
    "PlannerStateSnapshot",
    "QualitativeRelationBudgetPolicy",
    "RELATION_BUDGET_POLICIES",
    "REQUIRED_ESTIMATES",
    "RESOURCE_DISCLAIMER",
    "RelationBudgetCalibration",
    "RelationBudgetConfig",
    "RelationBudgetPlan",
    "RelationBudgetResult",
    "RelationBudgetScheduler",
    "ReplayReconciliation",
    "ReservationStatus",
    "RiskBudgetDemand",
    "SCHEDULER_VERSION",
    "SpecialReservePurpose",
    "StateBinningSpec",
    "StopReason",
    "SubCall",
    "SuccessorDiagnostics",
    "SuccessorStat",
    "build_action_catalog",
    "build_micro_planner",
    "build_plan",
    "build_relation_budget_scheduler",
    "classify_generation_record",
    "collect_catalog",
    "core_action_family",
    "generation_call",
    "load_calibrations",
    "load_history",
    "load_planner_calibration",
    "m11_actions",
    "m17_actions",
    "m18_actions",
    "m7_actions",
    "owner_action_families",
    "relation_policy",
    "replay_physical_calls",
    "reservation_id",
    "risk_demand",
    "score_label_call",
    "specialist_actions",
    "specialist_verification_plan",
    "state_bin_key",
    "state_signature",
    "structural_check_plan",
    "total_calls",
    "utility",
    "validate_bins",
]
