"""One active architecture: Mistral-Small-3.2-24B + Qwen3.5-4B, calibrated.

The heterogeneous portfolio - Gemma-3-12B, Nemotron-Nano-9B-v2, Qwen3.5-9B -
was measured on the official TEST and scored 0.3346 against the two-model
baseline's 0.4499. It is a completed negative ablation, and Audit 0066 retired
its executable path: the `portfolio` model strategy, the `DIRECT_UNCALIBRATED`
integration mode, the three-runtime pipeline, the direct readiness gate and the
Nemotron CUDA dependencies.

This file is the guard against any of that coming back by accident. It asserts
the *absence* of the retired paths as carefully as it asserts the presence of
the baseline, because a dead branch that can still select an unaudited model is
worse than one that was never removed.

Historical audits describing the experiment are untouched and remain evidence;
nothing here reads or rewrites them.
"""

from __future__ import annotations

import ast
import hashlib
import json
import sys

import pytest
import yaml

from cover_kbc.integration_mode import IntegrationMode
from cover_kbc.paths import REPO_ROOT
from cover_kbc.types import ModelRole

SRC = REPO_ROOT / "src" / "cover_kbc"
SCRIPTS = REPO_ROOT / "scripts"
EXPERIMENTS = REPO_ROOT / "configs" / "experiments"
CALIBRATION = REPO_ROOT / "configs" / "calibration"

#: The one active pair, with the counts this repository already verified.
BASELINE_ENUMERATOR = "mistralai/Mistral-Small-3.2-24B-Instruct-2506"
BASELINE_ENUMERATOR_REV = "95a6d26c4bfb886c58daf9d3f7332c857cb27b43"
BASELINE_ENUMERATOR_PARAMS = 24_011_361_280
BASELINE_VERIFIER = "Qwen/Qwen3.5-4B"
BASELINE_VERIFIER_REV = "851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a"
BASELINE_VERIFIER_PARAMS = 4_659_865_088
BASELINE_TOTAL = 28_671_226_368
PARAMETER_LIMIT = 32_000_000_000

#: The retired checkpoints. No experiment config may resolve any of them.
RETIRED_MODELS = (
    "google/gemma-3-12b-it",
    "nvidia/NVIDIA-Nemotron-Nano-9B-v2",
    "Qwen/Qwen3.5-9B",
)

#: The three official production configs.
PRODUCTION_CONFIGS = (
    "cover_kbc_v2_train_collection.yaml",
    "cover_kbc_v2_validation.yaml",
    "cover_kbc_v2_test.yaml",
)

#: The current official TEST snapshot (Audit 0064). Unchanged by this cleanup.
TEST_ROWS = 475
TEST_SHA256 = "67c31c8388c585634df55500612f522ad42da6735d4c89eb59a9ef5a39f043f1"
TEST_IDENTITY = "69d7d7cbafed0a612a51c13ad42dafc448705af5d5522cd24ef6334e9ad78640"

#: The TRAIN-derived baseline calibration. Not regenerated by this cleanup.
BASELINE_CALIBRATION_SHA256 = {
    "m20_relation_budget.json":
        "8110fccb4c3e85a942f5fc89a50f680bea72e8b6d1e83b1fa2c47d670ec15c68",
    "m21_historical_bins.json":
        "d6d19493b0b82299e5c73bd0f37e2b3758c4a80894b6b1bdf9fa57139fbcd071",
    "m21_planner_calibration.json":
        "36315cd72a2c31bcbc61bb1ada9f2e74d8980baa575f6221d92bf8b144f9ce05",
}


def _load(name: str) -> dict:
    return yaml.safe_load((EXPERIMENTS / name).read_text())


def _executable_source(path) -> str:
    """A module's code with docstrings removed.

    Scanned rather than raw text because this repository documents what it
    deliberately does *not* do - and after a retirement it documents what it
    used to. A prose scan would flag the record of the removal as the thing.
    """
    tree = ast.parse(path.read_text())
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef,
                                 ast.AsyncFunctionDef)):
            continue
        body = getattr(node, "body", [])
        if (body and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)):
            node.body = body[1:] or [ast.Pass()]
    return ast.unparse(tree)


# ==========================================================================
# exactly two active models
# ==========================================================================


@pytest.mark.parametrize("name", PRODUCTION_CONFIGS)
def test_every_production_config_declares_exactly_the_baseline_pair(name) -> None:
    profile = _load(name)["model_profile"]
    assert set(profile) == {"enumerator", "verifier"}, name
    assert profile["enumerator"]["model_id"] == BASELINE_ENUMERATOR
    assert profile["enumerator"]["revision"] == BASELINE_ENUMERATOR_REV
    assert profile["verifier"]["model_id"] == BASELINE_VERIFIER
    assert profile["verifier"]["revision"] == BASELINE_VERIFIER_REV


@pytest.mark.parametrize("name", PRODUCTION_CONFIGS)
def test_the_parameter_counts_and_total_are_the_verified_ones(name) -> None:
    config = _load(name)
    profile = config["model_profile"]
    assert profile["enumerator"]["published_total_parameters"] == (
        BASELINE_ENUMERATOR_PARAMS)
    assert profile["verifier"]["published_total_parameters"] == (
        BASELINE_VERIFIER_PARAMS)
    assert BASELINE_ENUMERATOR_PARAMS + BASELINE_VERIFIER_PARAMS == BASELINE_TOTAL
    assertion = config["budget_assertion"]
    assert assertion["total_published_parameters"] == BASELINE_TOTAL
    assert assertion["limit"] == PARAMETER_LIMIT
    assert assertion["legal"] is True


def test_the_budget_audit_accepts_the_baseline_pair() -> None:
    from cover_kbc.models.base import ModelSpec
    from cover_kbc.models.budget import audit_parameter_budget

    specs = [
        ModelSpec(model_id=BASELINE_ENUMERATOR,
                  published_total_parameters=BASELINE_ENUMERATOR_PARAMS,
                  family="mistral", role="enumerator", is_neural=True,
                  parameter_source="url", parameter_source_verified=True),
        ModelSpec(model_id=BASELINE_VERIFIER,
                  published_total_parameters=BASELINE_VERIFIER_PARAMS,
                  family="qwen", role="verifier", is_neural=True,
                  parameter_source="url", parameter_source_verified=True),
    ]
    audit = audit_parameter_budget(specs)
    assert audit.passed, audit.problems
    assert audit.total_parameters == BASELINE_TOTAL


def test_the_role_vocabulary_is_back_to_two_neural_roles() -> None:
    """The portfolio's three logical roles retired with it."""
    assert [role.value for role in ModelRole] == [
        "enumerator", "verifier", "stub", "none"]


# ==========================================================================
# no active path can resolve a retired model
# ==========================================================================


@pytest.mark.parametrize("model_id", RETIRED_MODELS)
def test_no_experiment_config_names_a_retired_model(model_id) -> None:
    for path in sorted(EXPERIMENTS.glob("*.yaml")):
        assert model_id not in path.read_text(), f"{path.name}: {model_id}"


@pytest.mark.parametrize("model_id", RETIRED_MODELS)
def test_no_executable_source_names_a_retired_model(model_id) -> None:
    for root in (SRC, SCRIPTS):
        for path in root.rglob("*.py"):
            assert model_id not in _executable_source(path), f"{path}: {model_id}"


def test_the_portfolio_experiment_configs_are_gone() -> None:
    assert sorted(p.name for p in EXPERIMENTS.glob("*portfolio*")) == []


def test_the_portfolio_modules_are_gone() -> None:
    for name in ("strategy.py", "bakeoff.py"):
        assert not (SRC / "models" / name).exists(), name


def test_no_model_strategy_abstraction_remains() -> None:
    for root in (SRC, SCRIPTS):
        for path in root.rglob("*.py"):
            code = _executable_source(path)
            for token in ("ModelStrategy", "model_strategy",
                          "models.strategy", "models.bakeoff"):
                assert token not in code, f"{path}: {token}"


def test_the_runner_offers_no_strategy_flag() -> None:
    source = (SCRIPTS / "run_cover.py").read_text()
    assert "--model-strategy" not in source
    assert "PORTFOLIO" not in source


# ==========================================================================
# no active runtime mode resolves DIRECT_UNCALIBRATED
# ==========================================================================


def test_the_execution_mode_vocabulary_is_back_to_three() -> None:
    assert [mode.value for mode in IntegrationMode] == [
        "shadow", "production", "train_calibration_collection_only"]
    assert not hasattr(IntegrationMode, "DIRECT_UNCALIBRATED")


def test_direct_uncalibrated_is_unparseable() -> None:
    from cover_kbc.integration_mode import IntegrationModeError, parse_mode

    with pytest.raises(IntegrationModeError):
        parse_mode("direct_uncalibrated", module="test")


def test_no_executable_source_mentions_the_direct_mode() -> None:
    for root in (SRC, SCRIPTS):
        for path in root.rglob("*.py"):
            code = _executable_source(path)
            for token in ("DIRECT_UNCALIBRATED", "direct_uncalibrated",
                          "is_direct", "FULL_TEST_DIRECT_READY",
                          "evaluate_direct_test_readiness"):
                assert token not in code, f"{path}: {token}"


def test_the_direct_readiness_state_and_gate_are_gone() -> None:
    from cover_kbc.controller_calibration import readiness

    assert not hasattr(readiness.ReadinessState, "FULL_TEST_DIRECT_READY")
    assert not hasattr(readiness, "evaluate_direct_test_readiness")
    report = readiness.ReadinessReport(readiness.ReadinessState.NOT_READY)
    assert "may_run_test_direct" not in report.to_json()


def test_the_pipeline_takes_no_third_runtime() -> None:
    import inspect

    from cover_kbc.pipeline import CoverPipeline

    parameters = inspect.signature(CoverPipeline.__init__).parameters
    assert "verifier_runtime" in parameters
    assert "structural_runtime" not in parameters


def test_the_manifest_carries_no_strategy_or_controller_fields() -> None:
    from cover_kbc.runtime.manifest import RunManifest

    payload = RunManifest(run_id="r", experiment="e", split="test",
                          seed=1).to_json()
    for key in ("model_strategy", "model_strategy_requested",
                "model_strategy_status", "model_strategy_profile",
                "controller_mode", "production_calibrated",
                "calibration_owner", "experiment_variant"):
        assert key not in payload, key


# ==========================================================================
# the baseline controller and calibration are untouched
# ==========================================================================


@pytest.mark.parametrize("name,expected",
                         sorted(BASELINE_CALIBRATION_SHA256.items()))
def test_the_baseline_calibration_artifacts_are_unchanged(name, expected) -> None:
    assert hashlib.sha256(
        (CALIBRATION / name).read_bytes()).hexdigest() == expected


def test_the_baseline_still_reaches_full_test_ready() -> None:
    from cover_kbc.controller_calibration.readiness import (
        ReadinessState,
        evaluate_test_readiness,
    )

    config = _load("cover_kbc_v2_test.yaml")
    provenance = config["calibration_provenance"]
    report = evaluate_test_readiness(
        config, base_dir=EXPERIMENTS, split="test",
        expected_collection_repo_sha=provenance["collection_repo_sha"],
        expected_derivation_repo_sha=provenance["derivation_repo_sha"])
    assert report.state is ReadinessState.FULL_TEST_READY, report.blockers
    assert list(report.blockers) == []


def test_the_baseline_still_reaches_full_validation_ready() -> None:
    from cover_kbc.controller_calibration.readiness import (
        ReadinessState,
        evaluate_validation_readiness,
    )

    config = _load("cover_kbc_v2_validation.yaml")
    provenance = config["calibration_provenance"]
    report = evaluate_validation_readiness(
        config, base_dir=EXPERIMENTS, split="val",
        expected_collection_repo_sha=provenance["collection_repo_sha"],
        expected_derivation_repo_sha=provenance["derivation_repo_sha"])
    assert report.state is ReadinessState.FULL_VALIDATION_READY, report.blockers


def test_the_calibration_loads_and_stays_train_calibrated() -> None:
    from cover_kbc.control.budget_types import CalibrationSource
    from cover_kbc.controller_calibration.production import (
        load_production_calibration,
    )

    config = _load("cover_kbc_v2_test.yaml")
    calibration = load_production_calibration(config, base_dir=EXPERIMENTS)
    assert len(calibration.budgets) == 6
    assert len(calibration.history.bins) == 64
    assert calibration.planner.lookahead_depth == 1
    for budget in calibration.budgets.values():
        assert budget.calibration_source is CalibrationSource.TRAIN_CALIBRATED


def test_the_calibrated_controller_still_governs_production() -> None:
    """The baseline is calibrated, not converted into an uncalibrated system."""
    for name in ("cover_kbc_v2_validation.yaml", "cover_kbc_v2_test.yaml"):
        config = _load(name)
        assert config["relation_budget_scheduler"]["mode"] == "production"
        assert config["micro_planner"]["mode"] == "production"
        assert config["layer6_integration"]["enabled"] is True

    import inspect

    from cover_kbc.pipeline import CoverPipeline

    # Module 21 owns action choice in production, and only there.
    source = inspect.getsource(CoverPipeline._select_actions)
    assert "self.integration_mode.is_production" in source
    assert "_plan_next_action" in source
    # Module 20 still precharges every production action.
    precharge = inspect.getsource(CoverPipeline._precharge)
    assert "self.integration_mode.is_collection" in precharge
    assert "_budget_ledger_for" in precharge


def test_physical_accounting_is_unchanged() -> None:
    from cover_kbc.pipeline import CoverPipeline

    assert CoverPipeline.PHYSICAL_COUNTERS == (
        "enumerator_calls", "verifier_calls", "physical_calls",
        "prompt_tokens", "generated_tokens")
    source = (SRC / "pipeline.py").read_text()
    body = source[source.index("def run(self, queries"):]
    assert body.index("except AccountingInvariantError:") < body.index(
        "except Exception as exc:")


# ==========================================================================
# the current official TEST snapshot survives the cleanup
# ==========================================================================


def test_the_official_test_snapshot_is_unchanged() -> None:
    path = REPO_ROOT / "benchmark" / "data" / "test.jsonl"
    raw = path.read_bytes()
    rows = [json.loads(line) for line in raw.decode().splitlines()
            if line.strip()]
    assert len(rows) == TEST_ROWS
    assert hashlib.sha256(raw).hexdigest() == TEST_SHA256
    assert all(row["ObjectEntities"] == [] for row in rows)


def test_the_baseline_test_config_pins_the_current_snapshot() -> None:
    dataset = _load("cover_kbc_v2_test.yaml")["test_dataset"]
    assert dataset["rows"] == TEST_ROWS
    assert dataset["sha256"] == TEST_SHA256
    assert dataset["identity_sha256"] == TEST_IDENTITY
    assert dataset["blind"] is True


def test_the_packager_pins_the_current_snapshot() -> None:
    source = (SCRIPTS / "package_submission.py").read_text()
    assert f'"rows": {TEST_ROWS},' in source
    assert TEST_SHA256 in source
    assert TEST_IDENTITY in source
    # ...and the historical 477-row snapshot is not reinstated.
    assert "849f565d" not in source
    assert "1bce6d40" not in source


def test_the_package_contract_is_exactly_predictions_jsonl() -> None:
    source = (SCRIPTS / "package_submission.py").read_text()
    assert 'ARCHIVE_MEMBER = "predictions.jsonl"' in source
    assert "members != [ARCHIVE_MEMBER]" in source


def test_the_evaluator_is_untouched() -> None:
    evaluator = REPO_ROOT / "benchmark" / "evaluate.py"
    assert hashlib.sha256(evaluator.read_bytes()).hexdigest() == (
        "2d592ae177c7b230922bb959da7a8ee1c4c662bf72a99d4dbd0cf62170ff9e22")


# ==========================================================================
# the historical evidence survives too
# ==========================================================================


def test_the_experiment_audits_are_preserved() -> None:
    """Retiring the code does not retire the record that it was measured."""
    audits = REPO_ROOT / "docs" / "audits"
    for name in ("0061-model-strategy-baseline-and-portfolio.md",
                 "0062-portfolio-v2-qwen9-production-preparation.md",
                 "0063-portfolio-direct-test-without-m20-m21.md",
                 "0064-official-test-snapshot-475-synchronization.md",
                 "0065-portfolio-real-weight-runtime-reproducibility.md"):
        assert (audits / name).is_file(), name


def test_one_canonical_runner_and_one_pipeline_class() -> None:
    assert (SCRIPTS / "run_cover.py").is_file()
    classes = [line for path in SRC.rglob("*.py")
               for line in path.read_text().splitlines()
               if line.startswith("class CoverPipeline")]
    assert classes == ["class CoverPipeline:"]


def test_the_baseline_cli_needs_no_experimental_flag(tmp_path,
                                                     monkeypatch) -> None:
    """`run_cover.py --config <baseline>` and nothing else."""
    import importlib.util

    path = SCRIPTS / "run_cover.py"
    sys.path.insert(0, str(SCRIPTS))
    try:
        spec = importlib.util.spec_from_file_location("run_cover_restored", path)
        runner = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(runner)
    finally:
        sys.path.remove(str(SCRIPTS))

    built: list[str] = []

    class _Built(RuntimeError):
        pass

    def stub(block):
        built.append(block["model_id"])
        raise _Built("reached build_runtime")

    monkeypatch.setattr(runner, "build_runtime", stub)
    monkeypatch.setattr(runner, "require_huggingface_runtime",
                        lambda *a, **k: None)
    monkeypatch.setattr(sys, "argv", [
        "run_cover.py", "--config", str(EXPERIMENTS / "cover_kbc_v2_test.yaml")])
    with pytest.raises(_Built):
        runner.main()
    assert built == [BASELINE_ENUMERATOR]
