"""Module 11 probe templates - generic frames filled from Module 10.

Three templates, one per proposal probe family (§7.2). Each is a *generic*
frame: it contains no relation name, no relation definition and no factual
content of its own. Everything relation-specific is read from the structured
:class:`~cover_kbc.query_intelligence.prompt_types.PromptProgram` - Module 10
remains the single source of relation language, and the rendered preview is
never parsed back into structure.

A test asserts no official relation name appears in this file.

**Semantic cues are prompt text, never queries.** They are placed inside the
prompt so the frozen model's own attention moves towards the right region of
its weights. Nothing here is sent anywhere: this module imports no network
client and performs no I/O.
"""

from __future__ import annotations

from cover_kbc.query_intelligence.prompt_types import (
    ObjectKind,
    PromptProgram,
)
from cover_kbc.query_intelligence.retrieval_types import ExpectedOutputKind

#: Shared system prompt for every probe. States the closed-book rule outright so
#: the model is never invited to imagine a retrieval step, and states that this
#: is recall rather than a final answer.
RETRIEVAL_SYSTEM_PROMPT = (
    "You answer from your own internal knowledge only. You have no access to "
    "search, documents, databases or external tools. When you are not sure, say "
    "so rather than inventing a plausible answer. Follow the requested output "
    "format exactly and add no commentary."
)


def _bullets(lines) -> str:
    return "\n".join(f"- {line}" for line in lines)


def _subject_block(program: PromptProgram) -> str:
    """The subject, plus Module 10's losslessness instructions."""
    block = [f'Subject: "{program.subject}"']
    if program.subject_directives:
        block.append(
            _bullets(entry.instruction for entry in program.subject_directives)
        )
    return "\n".join(block)


def render_pseudo_memory(program: PromptProgram) -> str:
    """Probe family 1: "the model writes a relation-focused memory sketch".

    Prose on purpose. The proposal is explicit that the sketch is an acquisition
    artifact - "the sketch does not itself create a support edge" - so this asks
    for recall, not for an answer in the output schema.
    """
    parts = [
        program.task_semantics.relation_focus,
        "",
        program.task_semantics.definition,
        "",
        _subject_block(program),
        "",
        "Recall what you know about this subject only insofar as it bears on the "
        "relation above. Do not state unrelated facts about it.",
    ]
    if program.semantic_cues:
        parts += ["", "This relation is ordinarily phrased as: "
                  + ", ".join(program.semantic_cues) + "."]
    if program.negative_anchors:
        parts += ["These phrasings describe something else and are not this "
                  "relation: " + ", ".join(program.negative_anchors) + "."]
    parts += [
        "",
        "Write at most three sentences of continuous prose. Do not produce a "
        "list. If you recall nothing relevant, write exactly: NO RECOLLECTION",
    ]
    return "\n".join(parts)


def render_self_ask(program: PromptProgram) -> str:
    """Probe family 2: self-ask decomposition, answered by the frozen model.

    The sub-questions come from Module 10's step-back
    :class:`QuerySpecification`, which the proposal (§6.4) says "becomes the
    branch plan for M11-M15". They are rendered, never generated by a model.

    The final answer is deliberately not requested: this probe exists to surface
    the intermediate recall a specialist will later work from.
    """
    spec = program.query_specification
    parts = [
        spec.relation_focus,
        "",
        program.task_semantics.definition,
        "",
        _subject_block(program),
        "",
        spec.semantic_question,
        "",
        "Answer each of these sub-questions about the subject above, one per line:",
        _bullets(spec.abstraction_cues),
        "",
        "Output format: one line per sub-question, exactly as",
        "Q: <sub-question>",
        "A: <your answer, or UNKNOWN>",
        "Do not add a summary and do not answer the main question directly.",
    ]
    return "\n".join(parts)


def render_query_rewrite(program: PromptProgram) -> str:
    """Probe family 3: a rewrite conditioned on negative constraints.

    The proposal specifies rewriting "using a missing facet/negative constraint
    instead of merely changing the random seed", so this frame is built around
    Module 10's exclusions and near-miss anchors rather than around a reworded
    question. That is what makes it a structurally different probe rather than
    a second sample of the first.
    """
    parts = [
        program.task_semantics.relation_focus,
        "",
        program.task_semantics.definition,
        f"Expected answer type: {program.task_semantics.answer_type}.",
        "",
        _subject_block(program),
        "",
        "Counts as correct:",
        _bullets(program.positive_constraints),
        "",
        "Does NOT count:",
        _bullets(program.negative_constraints),
    ]
    if program.negative_anchors:
        parts += [
            "",
            "Do not answer as if the question were about: "
            + ", ".join(program.negative_anchors) + ".",
        ]
    if program.risk_directives:
        parts += [
            "",
            _bullets(entry.instruction for entry in program.risk_directives),
        ]
    parts += ["", program.output_contract]
    return "\n".join(parts)


def expected_output_kind(program: PromptProgram) -> ExpectedOutputKind:
    """The shape a rewrite probe asks for, from Module 10's answer schema."""
    schema = program.answer_schema
    if schema.object_kind is ObjectKind.NUMBER:
        return ExpectedOutputKind.NUMBER
    return ExpectedOutputKind.OBJECT_LIST


#: The sentinel a pseudo-memory probe returns when it recalls nothing.
NO_RECOLLECTION = "NO RECOLLECTION"
